safe-points = [
    { frequency = 350, voltage = 570 },
    { frequency = 860, voltage = 600 },
    { frequency = 1090, voltage = 650 },
    { frequency = 1280, voltage = 700 },
    { frequency = 1460, voltage = 750 },
    { frequency = 1620, voltage = 800 },
    { frequency = 1760, voltage = 850 },
    { frequency = 1890, voltage = 900 },
    { frequency = 2030, voltage = 950 },
    { frequency = 2090, voltage = 975 },
    { frequency = 2140, voltage = 1000 },
    { frequency = 2230, voltage = 1050 },
]

[timing]
burst-samples = 20
ramp-up-samples = 64
ramp-down-samples = 256
intervals = { sample = 2000, adjust = 8000, finetune = 50000 }
ramp-rates = { burst = 1000, up = 50, up-medium = 25, up-slow = 10, up-crawl = 2, down = 0.2 }

[frequency-thresholds]
adjust = 100
finetune = 25

[load-target]
upper = 0.90
medium = 0.80
slow = 0.70
crawl = 0.60
lower = 0.40

[thermal]
monitor_interval = 1000
max_safe_temp = 85.0
emergency_temp = 95.0
fan_control_index = 1

[thermal.fan-control]
enabled = true
curve = [
    [35.0, 10],
    [45.0, 20],
    [55.0, 40],
    [65.0, 60],
    [75.0, 80],
    [85.0, 100],
]